services:
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph
    container_name: grep-oxigraph
    ports:
      - "7878:7878"
    volumes:
      - oxigraph_data:/data
    restart: unless-stopped
    command: serve --location /data/oxidb --bind 0.0.0.0:7878

volumes:
  oxigraph_data:
